language: python
python:
  - "3.4"
script: 
  - python3 cryptographer.py -e -p pass -k 10 -i test -o test.encrypted
  - test $(md5sum test| cut -f 1 -d ' ') != $(md5sum test.encrypted | cut -f 1 -d ' ')
  - python3 cryptographer.py -d -p pass -k 10 -i test.encrypted -o test.decrypted
  - test $(md5sum test| cut -f 1 -d ' ') = $(md5sum test.decrypted | cut -f 1 -d ' ')
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/68bacaf2dfee0a49a3f6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

